package org.shzhong.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.shzhong.mybatis.domain.GuideAd;
import org.shzhong.mybatis.domain.GuideAdExample;

public interface GuideAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    long countByExample(GuideAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int deleteByExample(GuideAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int insert(GuideAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int insertSelective(GuideAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    List<GuideAd> selectByExample(GuideAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    GuideAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") GuideAd record, @Param("example") GuideAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int updateByExample(@Param("record") GuideAd record, @Param("example") GuideAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int updateByPrimaryKeySelective(GuideAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_ad
     *
     * @mbg.generated Thu Nov 29 16:43:22 CST 2018
     */
    int updateByPrimaryKey(GuideAd record);
}